export const EDIT_LOGIN_INPUT_VALUE = "EDIT_LOGIN_INPUT_VALUE";
export const EDIT_REGISTER_INPUT_VALUE = "EDIT_REGISTER_INPUT_VALUE";
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";